create table if not exists app_user (
  id bigint generated by default as identity primary key,
  username varchar(64) not null unique,
  password_hash varchar(255) not null,
  display_name varchar(64) not null,
  role varchar(32) not null,
  enabled boolean not null default true,
  created_at timestamp not null,
  updated_at timestamp not null
);

create table if not exists source_project (
  id bigint generated by default as identity primary key,
  project_key varchar(64) not null unique,
  project_name varchar(128) not null,
  repo_url varchar(255) not null,
  release_branch varchar(128) not null,
  release_commit varchar(64) not null,
  source_type varchar(32) not null,
  status varchar(32) not null,
  summary varchar(512) not null,
  created_at timestamp not null,
  updated_at timestamp not null
);

create table if not exists environment (
  id bigint generated by default as identity primary key,
  env_code varchar(64) not null unique,
  env_name varchar(128) not null,
  env_kind varchar(32) not null,
  base_url varchar(255) not null,
  blue_url varchar(255),
  green_url varchar(255),
  current_color varchar(16) not null,
  supports_blue_green boolean not null default false,
  announce_file_exists boolean not null default false,
  health_status varchar(32) not null,
  notes varchar(512) not null,
  created_at timestamp not null,
  updated_at timestamp not null
);

create table if not exists component (
  id bigint generated by default as identity primary key,
  component_key varchar(64) not null unique,
  component_name varchar(128) not null,
  component_type varchar(32) not null,
  config_dir varchar(255) not null,
  data_dir varchar(255) not null,
  deploy_path varchar(255) not null,
  support_incremental boolean not null default true,
  support_rollback boolean not null default true,
  support_blue_green boolean not null default false,
  is_extension boolean not null default false,
  is_core boolean not null default false,
  install_order integer not null,
  rollback_order integer not null,
  notes varchar(512) not null,
  created_at timestamp not null,
  updated_at timestamp not null
);

create table if not exists release_change (
  id bigint generated by default as identity primary key,
  change_code varchar(64) not null unique,
  title varchar(128) not null,
  project_branch varchar(128) not null,
  release_type varchar(32) not null,
  target_env_code varchar(64) not null,
  target_color varchar(16) not null,
  status varchar(32) not null,
  developer_username varchar(64) not null,
  developer_display_name varchar(64) not null,
  reviewer_a_username varchar(64),
  reviewer_b_username varchar(64),
  review_mode varchar(32) not null,
  demo_required boolean not null default false,
  demo_confirmed boolean not null default false,
  risk_level varchar(32) not null,
  summary varchar(512) not null,
  content_json text not null,
  current_step varchar(64) not null,
  final_message varchar(512) not null,
  created_at timestamp not null,
  updated_at timestamp not null,
  submitted_at timestamp,
  approved_at timestamp,
  switched_at timestamp,
  verified_at timestamp,
  released_at timestamp,
  rolled_back_at timestamp
);

create table if not exists release_node (
  id bigint generated by default as identity primary key,
  change_id bigint not null,
  node_key varchar(64) not null,
  component_key varchar(64) not null,
  component_name varchar(128) not null,
  node_type varchar(32) not null,
  node_order integer not null,
  rollback_order integer not null,
  status varchar(32) not null,
  action_type varchar(32) not null,
  host_name varchar(128) not null,
  command_hint varchar(255) not null,
  config_dir varchar(255) not null,
  data_dir varchar(255) not null,
  detail_json text not null,
  created_at timestamp not null,
  updated_at timestamp not null,
  constraint fk_release_node_change foreign key (change_id) references release_change(id) on delete cascade
);

create table if not exists review_record (
  id bigint generated by default as identity primary key,
  change_id bigint not null,
  reviewer_username varchar(64) not null,
  reviewer_display_name varchar(64) not null,
  review_type varchar(32) not null,
  passed boolean not null,
  demo_required boolean not null default false,
  demo_confirmed boolean not null default false,
  comment varchar(512) not null,
  created_at timestamp not null,
  updated_at timestamp not null,
  constraint fk_review_change foreign key (change_id) references release_change(id) on delete cascade
);

create table if not exists demo_record (
  id bigint generated by default as identity primary key,
  change_id bigint not null,
  developer_username varchar(64) not null,
  reviewer_username varchar(64) not null,
  content varchar(512) not null,
  created_at timestamp not null,
  updated_at timestamp not null,
  constraint fk_demo_change foreign key (change_id) references release_change(id) on delete cascade
);

create table if not exists test_report (
  id bigint generated by default as identity primary key,
  change_id bigint not null,
  report_type varchar(32) not null,
  title varchar(128) not null,
  summary varchar(512) not null,
  detail_json text not null,
  ai_verdict varchar(128) not null,
  passed boolean not null,
  created_at timestamp not null,
  updated_at timestamp not null,
  constraint fk_report_change foreign key (change_id) references release_change(id) on delete cascade
);

create table if not exists environment_snapshot (
  id bigint generated by default as identity primary key,
  env_code varchar(64) not null,
  snapshot_name varchar(128) not null,
  snapshot_type varchar(32) not null,
  summary_json text not null,
  created_at timestamp not null,
  updated_at timestamp not null
);
